name: 'Reset'
description: 'Reset the branch to be based on another branch'
inputs:
  userName:
    description: 'git config user.name'
    default: 'Barry Mittens'
  userEmail:
    description: 'git config user.email'
    default: 'someone@test.com'
  source:
    description: 'The branch we want to be based on'
    required: true
  target:
    description: 'Branch that needs to be reset'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup git
      shell: bash
      run: |
          git config --local user.email "${{ inputs.userEmail }}"
          git config --local user.name "${{ inputs.userName }}"
    - name: Reset process
      shell: bash
      run: |
          echo "Fetching all"
          git fetch --all
          echo "Doing checkout of branch ${{ inputs.target }}"
          git switch ${{ inputs.target }}
          echo "Doing checkout of branch ${{ inputs.source }}"
          git switch ${{ inputs.source }}
          echo "Now resetting ${{ inputs.target }} to be based on ${{ inputs.source }}"
          git checkout -B ${{ inputs.target }}
          git commit --allow-empty -m "[skip actions]"
          echo "Force pushing to origin"
          git push origin ${{ inputs.target }} -f